CREATE TABLE IF NOT EXISTS public.wishlist (
  wishlist_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INT NOT NULL REFERENCES public.account(account_id) ON DELETE CASCADE,
  inv_id INT NOT NULL REFERENCES public.inventory(inv_id) ON DELETE CASCADE,
  UNIQUE(account_id, inv_id)
);
